#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

"""
falcond - The control daemon of the millenium falcon

Usage:
  falcond [-v | --verbose]
  falcond (-h | --help)
  falcond --version

Options:
  -v, --verbose  Show output on Stdout.
  -h, --help     Show this screen.
  --version      Show version.
"""

__author__ = "Ricardo (XenGi) Band"
__copyright__ = "Copyright 2013, Ricardo Band"
__credits__ = ["Ricardo (XenGi) Band", ]
__license__ = "MIT"
__version__ = "0.1.0-alpha"
__maintainer__ = "Ricardo (XenGi) Band"
__email__ = "xen@c-base.org"
__status__ = "Development"

import os
import sys
import time
import ConfigParser

import docopt
from jsonrpclib.SimpleJSONRPCServer import SimpleJSONRPCServer
try:
    import RPi.GPIO as GPIO
except RuntimeError:
    print 'Error importing RPi.GPIO! This is probably because you need ' \
          'superuser privileges. You can achieve this by using \'sudo\' ' \
          'to run your script'

LIGHT_R = 15  # IO 22
LIGHT_L = 16  # IO 23
LASER_R = 18  # IO 24
LASER_L = 22  # IO 25

class FalconServer(object):
    """
    Main class which holds the server code for the falcon.
    """
    def __init__(self, verbose):
        """
        Initialize main class with some stuff.
        """
        self._verbose = verbose
        if self._verbose:
            # bootup "animation"
            print('            .:+shhdd                                    /+   `/')
            print('        `/ymNNmmmmsmyso-..`                             /+   `/:')
            print('      -sNNds+oyo/:-..+md/+dho-                         :/:-  -:::')
            print('    .yNmy//::/+      oNs   ++hdo                      ///:-  -:/:/')
            print('   +NNy/os/o/` .:///sdm+-`/  `+.                     //o+/::-:/+o/:')
            print('  sNm+/dMMN+-++-`  .MMNMNms:-.                      /+::s+:+/:::-/o:')
            print(' oNm+omNMNNmm+ .:::dmmmmNNd/-                      ::++/o/////+//++.-  +o+')
            print('.NNo/mNNMNdNNNds-+oyysy/-o:  /                   .//-:-.:-/-:/o++/-----oso:')
            print('sNdNdNNNNdNNNdNdm/osss+os+d:  /                 .:::///::-+-://///...:/-o.-')
            print('hNdNdNNNMdNNd/y+/hNmdNm/ohNh--s                ::-..:::--./-://:/y+:-://---')
            print('hNh+dNNNNy--o`o+/hNmdNm/oyddNNN               :-----..-:--/-:/++o/://::::-')
            print('sNdNdNNNNd. .smyo+syys+oo-/mNNs              `/.--.----..:yyyy+/+/:--.--./`')
            print('.NNdmmNNNNy` .hmd/+osyhms+NNNh               `/////////o+-/sy/-+//////////')
            print(' +Nmo+mNNNNd/hNNds+/ohs/. :d+                `/:///+++o//--//-///++///:::+')
            print('  sNm+/dNNNNNmmmNNNN/  `-::`                 .-:---:/:-::+///oo::/o::---:-.')
            print('   /NNy/omNNNNNNmmmm:--.                     `--/-oso/-:+o++++o+::++:/---:`')
            print('    .yNms/ohmNNNNNNN        .+-               -:---:-:/+oooooooo+++/:-:-:.')
            print('      .sNNds+smmmmmm```.--:+shNo               .:.:::/+oo/+oo/+oo+:/::.:.')
            print('        `:smNNmmmmsooosyhdmNmy/`                `/:///+//:/o++://+////:`')
            print('            `:+syhddddhhs+:.                      .+s/::://++//::://:.')
            print('                                                     .-:://++s+/:-.i\n')
            print('The Falcon is booting...')
        self.config = ConfigParser.SafeConfigParser()
        self.config.read(['/etc/falcond.conf',
                          'falcond.conf'])

        self._sounds = self.config.get('falcond', 'sounddir')
        self._hostname = self.config.get('falcond', 'hostname')
        self._port = self.config.getint('falcond', 'port')

        if self._verbose:
            print 'Starting up the falcond software on Raspberry Pi v%s.' % GPIO.RPI_REVISION
        GPIO.setmode(GPIO.BOARD)
        GPIO.setwarnings(self._verbose)

        GPIO.setup(LIGHT_R, GPIO.OUT, initial=GPIO.LOW)
        GPIO.setup(LIGHT_L, GPIO.OUT, initial=GPIO.LOW)
        GPIO.setup(LASER_R, GPIO.OUT, initial=GPIO.LOW)
        GPIO.setup(LASER_L, GPIO.OUT, initial=GPIO.LOW)

        try:
            server = SimpleJSONRPCServer((self._hostname, self._port))

            server.register_function(self.help)
            server.register_function(self.set_lights)
            server.register_function(self.get_lights)
            server.register_function(self.fire_laser)
            server.register_function(self.get_sounds)
            server.register_function(self.play_sound)
            server.register_function(self.cinematic)

            server.serve_forever()
        except KeyboardInterrupt:
            sys.exit(0)
        finally:
            GPIO.cleanup()

    def help(self):
        """
        Lists all available functions
        """
        return('set_lights(left=True, right=True)' \
               'get_lights()' \
               'fire_laser(left=True, right=True, sound=True)' \
               'get_sounds()' \
               'play_sound(filename)' \
               'cinematic()')

    def set_lights(self, left=True, right=True):
        """
        Set the lights on or off
        """
        GPIO.output(LIGHT_L, left)
        GPIO.output(LIGHT_R, right)

    def get_lights(self):
        """
        Get current state of the lights
        """
        return [GPIO.input(LIGHT_L), GPIO.input(LIGHT_R)]

    def fire_laser(self, left=True, right=True, sound=True):
        """
        Fire the lasers
        """
        GPIO.output(LASER_L, left)
        GPIO.output(LASER_R, right)
        self.play_sound('laser.mp3')
        time.sleep(1)
        GPIO.output(LASER_L, False)
        GPIO.output(LASER_R, False)

    def get_sounds(self):
        """
        List all sound files in the falcon dir
        """
        sounds = [x[2] for x in os.walk(self._sounds)][0]
        return sounds

    def play_sound(self, sound):
        """
        Play a sound file
        """
        if sound in self.get_sounds():
            os.system('mpg123 %s' % os.path.join(self._sounds, sound))
        else:
            return False

    def cinematic(self):
        """
        Play a predefined animation
        """
        self.set_lights()
        self.play_sound('flyby.mp3')
        for i in range(4):
            self.fire_laser()
        time.sleep(1)
        self.set_lights(False, False)


if __name__ == '__main__':
    ARGS = docopt.docopt(__doc__, version=__version__)
    FALCON = FalconServer(ARGS['--verbose'])
