#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

"""
falcon - The control client for the millenium falcon

Usage:
  falcon [-v | --verbose]
  falcon (-h | --help)
  falcon --version

Options:
  -h, --help    Show this screen.
  --version     Show version.
"""

__author__ = "Ricardo (XenGi) Band"
__copyright__ = "Copyright 2013, Ricardo Band"
__credits__ = ["Ricardo (XenGi) Band", ]
__license__ = "MIT"
__version__ = "0.1.0-alpha"
__maintainer__ = "Ricardo (XenGi) Band"
__email__ = "xen@c-base.org"
__status__ = "Development"

import os
import sys

import docopt
import jsonrpclib

class FalconClient(object):
    """
    Main class which holds the client code for the falcon.
    """
    def __init__(self, verbose):
        """
        Initialize alle the things and play the cinematic
        """
        self._verbose = verbose

        try:
            server = jsonrpclib.Server('http://falcon.cbrp3.c-base.org:8080')
            server.cinematic()
        except KeyboardInterupt:
            sys.exit(0)


if __name__ == '__main__':
    ARGS = docopt.docopt(__doc__, version=__version__)
    FALCON = FalconServer(ARGS['--verbose'])
